name: PR Validation Dev Org

on:
  workflow_run:
    workflows: ["Auto Label PR"]
    types:
      - completed
    branches:
      - master

  workflow_dispatch:

jobs:
  validate-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Get PR labels from commit SHA
        id: get_labels
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const sha = '${{ github.event.workflow_run.head_sha }}';
            const prs = await github.rest.repos.listPullRequestsAssociatedWithCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: sha
            });

            if (prs.data.length === 0) {
              core.info('No PR found for this commit.');
              core.setOutput('should_deploy', 'false');
              return;
            }

            const labels = prs.data[0].labels.map(label => label.name);
            core.info(`Labels: ${labels.join(', ')}`);
            const shouldDeploy = labels.includes('dev');
            core.setOutput('should_deploy', shouldDeploy.toString());

      - name: Check out code
        uses: actions/checkout@v3
        if: steps.get_labels.outputs.should_deploy == 'true'

      - name: Install Salesforce CLI
        if: steps.get_labels.outputs.should_deploy == 'true'
        run: npm install sfdx-cli --global

      - name: Authenticate to Dev Org
        if: steps.get_labels.outputs.should_deploy == 'true'
        run: |
          echo "${{ secrets.SF_AUTH_URL_DEV }}" > authfile.txt
          sfdx force:auth:sfdxurl:store -f authfile.txt -a DevOrg

      - name: "🔍 Debug: Check Authenticated Orgs"
        if: steps.get_labels.outputs.should_deploy == 'true'
        run: sfdx force:org:list

      - name: Check-only Deploy to Dev Org
        if: steps.get_labels.outputs.should_deploy == 'true'
        run: |
          sfdx force:source:deploy -p force-app -u DevOrg --checkonly --testlevel RunLocalTests --wait 10
