name: PR Validation Dev Org

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled]
    branches:
      - master

jobs:
  validate-dev:
    # ⬇️ 최소 수정: labeled 이벤트일 때 'dev' 라벨이(부분일치) 있으면 실행
    if: |
      github.event_name == 'pull_request' &&
      (
        contains(join(github.event.pull_request.labels.*.name, ' '), 'dev') ||
        (github.event.action == 'labeled' && contains(github.event.label.name, 'dev'))
      )
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Salesforce CLI
        run: npm install sfdx-cli --global

      - name: Authenticate to Dev Org
        run: |
          echo "${{ secrets.SF_AUTH_URL_DEV }}" > authfile.txt
          sfdx force:auth:sfdxurl:store -f authfile.txt -a DevOrg

      - name: "🔍 Debug: Check Authenticated Orgs"
        run: sfdx force:org:list

      - name: Check-only Deploy to Dev Org
        run: |
          sfdx force:source:deploy -p force-app -u DevOrg --checkonly --testlevel RunLocalTests --wait 10
