name: PR Validation Against Dev Org

on:
  pull_request:
    branches:
      - master

jobs:
  validate-dev:
    if: contains(github.event.pull_request.labels.*.name, 'dev')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Salesforce CLI
        run: npm install sfdx-cli --global

      - name: Authenticate to Dev Org
        run: |
          echo "${{ secrets.SF_AUTH_URL_DEV }}" > authfile.txt
          sfdx auth:sfdxurl:store -f authfile.txt -a DevOrg

      - name: 🔍 Debug: Check Authenticated Orgs
        run: sfdx force:org:list

      - name: Check-only Deploy to Dev Org
        run: |
          sfdx force:source:deploy -p force-app -u DevOrg --checkonly --testlevel RunLocalTests --wait 10

      - name: Debug: Show Authenticated Orgs
        run: sfdx force:org:list
